insert into lecture(lecture_id, lecture_name, lecture_date, max_capacity, current_enrollment) values(1, '자바', '2024-06-29', 30, 0);
insert into lecture(lecture_id, lecture_name, lecture_date, max_capacity, current_enrollment) values(2, '파이썬', '2024-06-29', 30, 0);
insert into lecture(lecture_id, lecture_name, lecture_date, max_capacity, current_enrollment) values(3, '면접', '2024-07-06', 30, 0);
insert into lecture(lecture_id, lecture_name, lecture_date, max_capacity, current_enrollment) values(4, '클린 아키텍처', '2024-06-29',30, 0);
insert into lecture(lecture_id, lecture_name, lecture_date, max_capacity, current_enrollment) values(5, 'TDD', '2024-07-06', 30, 0);

insert into student(student_id, student_name) values(1, '전우치');
insert into student(student_id, student_name) values(2, '조승우');
insert into student(student_id, student_name) values(3, '홍길동');
insert into student(student_id, student_name) values(4, '류선재');
insert into student(student_id, student_name) values(5, '임 솔');
insert into student(student_id, student_name) values(6, '김희지');
insert into student(student_id, student_name) values(7, '이유미');
insert into student(student_id, student_name) values(8, '한가인');
insert into student(student_id, student_name) values(9, '김남길');
insert into student(student_id, student_name) values(10, '강호동');
insert into student(student_id, student_name) values(11, '전우치');
insert into student(student_id, student_name) values(12, '조승우');
insert into student(student_id, student_name) values(13, '홍길동');
insert into student(student_id, student_name) values(14, '류선재');
insert into student(student_id, student_name) values(15, '임 솔');
insert into student(student_id, student_name) values(16, '김희지');
insert into student(student_id, student_name) values(17, '이유미');
insert into student(student_id, student_name) values(18, '한가인');
insert into student(student_id, student_name) values(19, '김남길');
insert into student(student_id, student_name) values(20, '강호동');
insert into student(student_id, student_name) values(21, '전우치');
insert into student(student_id, student_name) values(22, '조승우');
insert into student(student_id, student_name) values(23, '홍길동');
insert into student(student_id, student_name) values(24, '류선재');
insert into student(student_id, student_name) values(25, '임 솔');
insert into student(student_id, student_name) values(26, '김희지');
insert into student(student_id, student_name) values(27, '이유미');
insert into student(student_id, student_name) values(28, '한가인');
insert into student(student_id, student_name) values(29, '김남길');
insert into student(student_id, student_name) values(30, '강호동');
insert into student(student_id, student_name) values(31, '전우치');
insert into student(student_id, student_name) values(32, '조승우');
insert into student(student_id, student_name) values(33, '홍길동');
insert into student(student_id, student_name) values(34, '류선재');
insert into student(student_id, student_name) values(35, '임 솔');
insert into student(student_id, student_name) values(36, '김희지');
insert into student(student_id, student_name) values(37, '이유미');
insert into student(student_id, student_name) values(38, '한가인');
insert into student(student_id, student_name) values(39, '김남길');
insert into student(student_id, student_name) values(40, '강호동');
insert into student(student_id, student_name) values(41, '전우치');
insert into student(student_id, student_name) values(42, '조승우');
insert into student(student_id, student_name) values(43, '홍길동');
insert into student(student_id, student_name) values(44, '류선재');
insert into student(student_id, student_name) values(45, '임 솔');
insert into student(student_id, student_name) values(46, '김희지');
insert into student(student_id, student_name) values(47, '이유미');
insert into student(student_id, student_name) values(48, '한가인');
insert into student(student_id, student_name) values(49, '김남길');
insert into student(student_id, student_name) values(50, '강호동');
